#!/bin/bash
# =============================================================================
# MoveX Frontend Build Script
# Builds frontend projects and deploys to /var/www/movex-fe
# =============================================================================

set -euo pipefail

# Load environment utilities
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/utils/env-loader.sh"

# Load environment variables
load_env

log_info "=========================================="
log_info "  MoveX Frontend Build Script"
log_info "=========================================="

# -----------------------------------------------------------------------------
# Configuration
# -----------------------------------------------------------------------------
SRC_DIR="${DEPLOY_DIR:-/opt/movex}/src"
FRONTEND_DIR="${FRONTEND_DIR:-/var/www/movex-fe}"
LOG_DIR="${LOG_DIR:-/var/log/movex}"

# Frontend project to build (primary)
PRIMARY_FE_PROJECT="movex-fe-masterdata"

# API URLs for production
API_BASE_URL="${SERVER_IP:-localhost}"
NGINX_API_PORT="${NGINX_API_PORT:-8080}"

# -----------------------------------------------------------------------------
# Functions
# -----------------------------------------------------------------------------

copy_frontend_env() {
    local project_dir="$1"
    local config_env="${PROJECT_ROOT}/config/frontend.env"
    local target_env="${project_dir}/.env"
    
    log_info "Setting up frontend environment..."
    
    # Check if custom frontend.env exists in config folder
    if [[ -f "${config_env}" ]]; then
        log_info "Copying frontend.env from config folder..."
        
        # Replace placeholder with actual server IP
        sed "s/YOUR_SERVER_IP/${SERVER_IP:-localhost}/g" "${config_env}" > "${target_env}"
        
        log_success "Copied: ${config_env} -> ${target_env}"
    else
        log_warning "Config file not found: ${config_env}"
        log_info "Generating production environment..."
        create_production_env "${project_dir}"
    fi
}

create_production_env() {
    local project_dir="$1"
    local env_file="${project_dir}/.env"
    
    log_info "Creating production environment file..."
    
    # Determine the base URL (use domain if available, otherwise IP)
    local BASE_URL="${SERVER_DOMAIN:-${SERVER_IP:-localhost}}"
    local API_URL="http://${BASE_URL}:${NGINX_API_PORT}"
    
    cat > "${env_file}" << EOF
# MoveX Frontend - Production Environment
# Auto-generated by build script

VITE_APP_ENV=production
VITE_DEBUG_MODE=false

# API Base URLs (via Nginx API Gateway)
VITE_API_BASE_URL=${API_URL}
VITE_AUTH_API_BASE_URL=${API_URL}/api/auth
VITE_OMS_API_BASE_URL=${API_URL}/api/oms
VITE_MASTERDATA_API_BASE_URL=${API_URL}/api/master-data
VITE_TMS_API_BASE_URL=${API_URL}/api/tms

# Prototype Mode disabled in production
VITE_PROTOTYPE_MODE=false
EOF

    log_success "Created: ${env_file}"
}

build_frontend() {
    local project_name="$1"
    local project_dir="${SRC_DIR}/${project_name}"
    local log_file="${LOG_DIR}/${project_name}-build.log"
    
    if [[ ! -d "${project_dir}" ]]; then
        log_error "Frontend project not found: ${project_dir}"
        return 1
    fi
    
    log_info "Building ${project_name}..."
    cd "${project_dir}"
    
    # Copy frontend environment from config folder
    copy_frontend_env "${project_dir}"
    
    # Install dependencies
    log_info "Installing dependencies..."
    if yarn install > "${log_file}" 2>&1; then
        log_success "Dependencies installed"
    else
        log_error "Failed to install dependencies. Check log: ${log_file}"
        return 1
    fi
    
    # Build production bundle
    log_info "Building production bundle..."
    if yarn build >> "${log_file}" 2>&1; then
        log_success "Built ${project_name} successfully"
        return 0
    else
        log_error "Failed to build ${project_name}. Check log: ${log_file}"
        tail -50 "${log_file}"
        return 1
    fi
}

deploy_frontend() {
    local project_name="$1"
    local project_dir="${SRC_DIR}/${project_name}"
    local dist_dir="${project_dir}/dist"
    
    if [[ ! -d "${dist_dir}" ]]; then
        log_error "Build output not found: ${dist_dir}"
        return 1
    fi
    
    log_info "Deploying ${project_name} to ${FRONTEND_DIR}..."
    
    # Backup existing files (if any)
    if [[ -d "${FRONTEND_DIR}" && "$(ls -A ${FRONTEND_DIR} 2>/dev/null)" ]]; then
        local backup_dir="${FRONTEND_DIR}.backup.$(date +%Y%m%d_%H%M%S)"
        log_info "Backing up existing files to: ${backup_dir}"
        mv "${FRONTEND_DIR}" "${backup_dir}"
    fi
    
    # Create frontend directory
    ensure_dir "${FRONTEND_DIR}"
    
    # Copy build output
    cp -r "${dist_dir}/"* "${FRONTEND_DIR}/"
    
    # Set proper permissions
    chown -R www-data:www-data "${FRONTEND_DIR}"
    chmod -R 755 "${FRONTEND_DIR}"
    
    log_success "Deployed to ${FRONTEND_DIR}"
}

# -----------------------------------------------------------------------------
# Pre-flight Checks
# -----------------------------------------------------------------------------

log_info "Checking prerequisites..."

# Check Node.js
if ! command_exists node; then
    log_error "Node.js is not installed. Run 01-setup-server.sh first."
    exit 1
fi

NODE_VERSION=$(node --version)
log_info "Node.js: ${NODE_VERSION}"

# Check Yarn
if ! command_exists yarn; then
    log_error "Yarn is not installed. Run 01-setup-server.sh first."
    exit 1
fi

YARN_VERSION=$(yarn --version)
log_info "Yarn: ${YARN_VERSION}"

# Check source directory
if [[ ! -d "${SRC_DIR}" ]]; then
    log_error "Source directory not found: ${SRC_DIR}"
    log_error "Run 02-clone-repos.sh first."
    exit 1
fi

# Create log directory
ensure_dir "${LOG_DIR}"

# -----------------------------------------------------------------------------
# Build Primary Frontend
# -----------------------------------------------------------------------------

log_info ""
log_info "=========================================="
log_info "  Building Frontend: ${PRIMARY_FE_PROJECT}"
log_info "=========================================="

if ! build_frontend "${PRIMARY_FE_PROJECT}"; then
    log_error "Frontend build failed"
    exit 1
fi

# -----------------------------------------------------------------------------
# Deploy to Web Directory
# -----------------------------------------------------------------------------

log_info ""
log_info "=========================================="
log_info "  Deploying to Web Directory"
log_info "=========================================="

if ! deploy_frontend "${PRIMARY_FE_PROJECT}"; then
    log_error "Frontend deployment failed"
    exit 1
fi

# -----------------------------------------------------------------------------
# Reload Nginx
# -----------------------------------------------------------------------------

log_info ""
log_info "Reloading Nginx configuration..."

if nginx -t 2>/dev/null; then
    systemctl reload nginx
    log_success "Nginx reloaded successfully"
else
    log_warning "Nginx config test failed. Please check configuration."
fi

# -----------------------------------------------------------------------------
# Summary
# -----------------------------------------------------------------------------

log_info ""
log_info "=========================================="
log_success "  Frontend Build & Deploy Complete!"
log_info "=========================================="
log_info ""
log_info "Deployed files:"
log_info "  Location: ${FRONTEND_DIR}"
log_info "  Files:    $(find ${FRONTEND_DIR} -type f | wc -l)"
log_info "  Size:     $(du -sh ${FRONTEND_DIR} | cut -f1)"
log_info ""
log_info "Access the frontend at:"
log_info "  http://${SERVER_IP:-localhost}:${NGINX_FRONTEND_PORT:-8084}"
log_info ""
log_info "Next step: Run ./05-deploy-all.sh or start Docker services manually"
